### ISSUE TITLE
What is MVP (Minimum Viable Product)?

### ISSUE THREAD

**Issue by lzblack** [DevangBafna/final_project_oim3640#1]
Also, how do you plan to store data?

**Comment by DevangBafna** [comment]
Minimum Viable Product is an expense tracker.

It will let you do the following:
1) Set up your budget
2) Track your expenses
3) Track Stock prices based on a ticker
4) Track Cryptocurrencies prices like Bitcoin
5) Track weather based on location
6) View spending by category and months

Planning to store data in a table in a database. One table for expenses, one table for users.
